    <option value="15ann">15th Anniversary</option>
    <option value="pl21">2021 Lunar New Year</option>
    <option value="war">A Guerra da Centelha / War of the Spark</option>
    <option value="warjp">A Guerra da Centelha (Japonês) / War of the Spark (Japanese)</option>
    <option value="5dn">A Quinta Aurora / Fifth Dawn</option>
    <option value="us">A Saga de Urza / Urza's Saga</option>
    <option value="afr">Adventures in the Forgotten Realms</option>
    <option value="asafr">Adventures in the Forgotten Realms (Art Series)</option>
    <option value="prafr">Adventures in the Forgotten Realms (Promo)</option>
    <option value="cbafr">Adventures in the Forgotten Realms (Variantes) / Adventures in the Forgotten Realms (Variants)</option>
    <option value="arb">Alara Reunida / Alara Reborn</option>
    <option value="yclb">Alchemy Horizons: Baldur's Gate</option>
    <option value="y22">Alchemy: Innistrad</option>
    <option value="yneo">Alchemy: Kamigawa</option>
    <option value="ysnc">Alchemy: New Capenna</option>
    <option value="ai">Alianças / Alliances</option>
    <option value="wl">Alisios / Weatherlight</option>
    <option value="mt">Alvorecer / Morningtide</option>
    <option value="akh">Amonkhet</option>
    <option value="akr">Amonkhet Remastered</option>
    <option value="at">Anthologies</option>
    <option value="aq">Antiquities</option>
    <option value="ajs">APAC Junior Series</option>
    <option value="ap">Apocalipse / Apocalypse</option>
    <option value="an">Arabian Nights</option>
    <option value="arc">Archenemy</option>
    <option value="e01">Archenemy: Nicol Bolas</option>
    <option value="anb">Arena Beginner Set</option>
    <option value="arena">Arena League</option>
    <option value="ana">Arena New Player Experience</option>
    <option value="dka">Ascensão das Trevas / Dark Ascension</option>
    <option value="roe">Ascensão dos Eldrazi / Rise of the Eldrazi</option>
    <option value="apac">Asia Pacific Land Program</option>
    <option value="bfz">Batalha por Zendikar / Battle for Zendikar</option>
    <option value="br">Battle Royale Box Set</option>
    <option value="bh">Battle the Horde</option>
    <option value="bbd">Battlebond</option>
    <option value="bd">Beatdown Box Set</option>
    <option value="uppq">Black Lotus Ultra Pro Puzzle Quest / Black Lotus Ultra Pro Puzzle Quest</option>
    <option value="chk">Campeões de Kamigawa / Champions of Kamigawa</option>
    <option value="pc">Caos Planar / Planar Chaos</option>
    <option value="uqc">Celebration Cards</option>
    <option value="q06">Challenger Decks 2022</option>
    <option value="cp">Champs</option>
    <option value="cuppq">Chaos Orb Ultra Pro Puzzle Quest / Chaos Orb Ultra Pro Puzzle Quest</option>
    <option value="ch">Chronicles</option>
    <option value="som">Cicatrizes de Mirrodin / Scars of Mirrodin</option>
    <option value="clash">Clash Pack</option>
    <option value="cstd">Coldsnap Theme Decks</option>
    <option value="ced">Collector's Edition</option>
    <option value="cmd">Commander</option>
    <option value="c13">Commander 2013</option>
    <option value="c14">Commander 2014</option>
    <option value="c15">Commander 2015</option>
    <option value="c16">Commander 2016</option>
    <option value="c17">Commander 2017</option>
    <option value="c18">Commander 2018</option>
    <option value="c19">Commander 2019</option>
    <option value="c20">Commander 2020</option>
    <option value="c21">Commander 2021</option>
    <option value="cbc21">Commander 2021 (Variantes) / Commander 2021 (Variants)</option>
    <option value="cma2">Commander Anthology</option>
    <option value="cm2">Commander Anthology 2018</option>
    <option value="cc2">Commander Collection: Black</option>
    <option value="cc1">Commander Collection: Green</option>
    <option value="cmr">Commander Legends</option>
    <option value="fecmr">Commander Legends (Foil Etched)</option>
    <option value="prcmr">Commander Legends (Promo)</option>
    <option value="cbcmr">Commander Legends (Variantes) / Commander Legends (Variants)</option>
    <option value="clb">Commander Legends: Batalha por Portal de Baldur / Commander Legends: Battle for Baldur's Gate</option>
    <option value="asclb">Commander Legends: Batalha por Portal de Baldur (Art Series) / Commander Legends: Battle for Baldur's Gate (Art Series)</option>
    <option value="blclb">Commander Legends: Batalha por Portal de Baldur (Borderless) / Commander Legends: Battle for Baldur's Gate (Borderless)</option>
    <option value="exclb">Commander Legends: Batalha por Portal de Baldur (Extended) / Commander Legends: Battle for Baldur's Gate (Extended)</option>
    <option value="feclb">Commander Legends: Batalha por Portal de Baldur (Foil Etched) / Commander Legends: Battle for Baldur's Gate (Foil Etched)</option>
    <option value="pclb">Commander Legends: Batalha por Portal de Baldur (Promo) / Commander Legends: Battle for Baldur's Gate (Promo)</option>
    <option value="rbclb">Commander Legends: Batalha por Portal de Baldur (Rulebook) / Commander Legends: Battle for Baldur's Gate (Rulebook)</option>
    <option value="tclb">Commander Legends: Batalha por Portal de Baldur (Tokens) / Commander Legends: Battle for Baldur's Gate (Tokens)</option>
    <option value="cma">Commander's Arsenal</option>
    <option value="ocm1">Commander's Arsenal Oversized</option>
    <option value="cfx">Confluência / Conflux</option>
    <option value="ps">Conjunção / Planeshift</option>
    <option value="cns">Conspiracy</option>
    <option value="cn2">Conspiracy: Take the Crown</option>
    <option value="m19">Core Set 2019</option>
    <option value="pm19">Core Set 2019 (Promo)</option>
    <option value="m20">Core Set 2020</option>
    <option value="pm20">Core Set 2020 (Promo)</option>
    <option value="m21">Core Set 2021 / Core Set 2021</option>
    <option value="m21pr">Core Set 2021 (Promo)</option>
    <option value="m21cb">Core Set 2021 (Variantes) / Core Set 2021 (Variants)</option>
    <option value="ds">Darksteel / Darksteel</option>
    <option value="10e">Décima Edição / Tenth Edition</option>
    <option value="dm">Deckmasters</option>
    <option value="dg">Defeat a God</option>
    <option value="wwk">Despertar do Mundo / Worldwake</option>
    <option value="frf">Destino Reescrito / Fate Reforged</option>
    <option value="dom">Dominaria</option>
    <option value="pdom">Dominaria (Promo)</option>
    <option value="dmu">Dominária Unida / Dominaria United</option>
    <option value="dmc">Dominária Unida Commander / Dominaria United Commander</option>
    <option value="2xm">Double Masters</option>
    <option value="pr2xm">Double Masters (Promo)</option>
    <option value="2x2">Double Masters 2022</option>
    <option value="bl2x2">Double Masters 2022 (Borderless)</option>
    <option value="fe2x2">Double Masters 2022 (Foil Etched)</option>
    <option value="p2x2">Double Masters 2022 (Promo)</option>
    <option value="tf2x2">Double Masters 2022 (Textured Foil)</option>
    <option value="t2x2">Double Masters 2022 (Tokens)</option>
    <option value="2xmvip">Double Masters VIP Edition</option>
    <option value="dw1">Draft Weekend</option>
    <option value="dtk">Dragões de Tarkir / Dragons of Tarkir</option>
    <option value="drc">Dragon Con</option>
    <option value="ddadvd">Duel Decks Anthology: Divine vs. Demonic</option>
    <option value="ddaevg">Duel Decks Anthology: Elves vs. Goblins</option>
    <option value="ddagvl">Duel Decks Anthology: Garruk vs. Liliana</option>
    <option value="ddajvc">Duel Decks Anthology: Jace vs. Chandra</option>
    <option value="ddh">Duel Decks: Ajani vs. Nicol Bolas</option>
    <option value="ddq">Duel Decks: Blessed vs. Cursed</option>
    <option value="dvd">Duel Decks: Divine vs. Demonic</option>
    <option value="ddf">Duel Decks: Elspeth vs. Tezzeret</option>
    <option value="evg">Duel Decks: Elves vs. Goblins</option>
    <option value="ddu">Duel Decks: Elves vs. Inventors</option>
    <option value="gvl">Duel Decks: Garruk vs. Liliana</option>
    <option value="ddl">Duel Decks: Heroes vs. Monsters</option>
    <option value="ddj">Duel Decks: Izzet vs. Golgari</option>
    <option value="jvc">Duel Decks: Jace vs. Chandra</option>
    <option value="ddm">Duel Decks: Jace vs. Vraska</option>
    <option value="ddo">Duel Decks: Kiora vs. Elspeth</option>
    <option value="ddg">Duel Decks: Knights vs. Dragons</option>
    <option value="ddt">Duel Decks: Merfolk vs. Goblins</option>
    <option value="dds">Duel Decks: Mind vs. Might</option>
    <option value="ddr">Duel Decks: Nissa vs. Ob Nixilis</option>
    <option value="pvc">Duel Decks: Phyrexia vs. The Coalition</option>
    <option value="ddk">Duel Decks: Sorin vs. Tibalt</option>
    <option value="ddn">Duel Decks: Speed vs. Cunning</option>
    <option value="ddi">Duel Decks: Venser vs. Koth</option>
    <option value="ddp">Duel Decks: Zendikar vs. Eldrazi</option>
    <option value="dpa">Duels of the Planeswalkers</option>
    <option value="eve">Entardecer / Eventide</option>
    <option value="ia">Era Glacial / Ice Age</option>
    <option value="ts">Espiral Temporal / Time Spiral</option>
    <option value="tsr">Espiral Temporal Remasterizada / Time Spiral Remastered</option>
    <option value="prtsr">Espiral Temporal Remasterizada (Promo) / Time Spiral Remastered (Promo)</option>
    <option value="ema">Eternal Masters</option>
    <option value="euro">European Land Program</option>
    <option value="ex">Êxodo / Exodus</option>
    <option value="e02">Explorers of Ixalan</option>
    <option value="fh">Face the Hydra</option>
    <option value="fe">Fallen Empires</option>
    <option value="sc">Flagelo / Scourge</option>
    <option value="afc">Forgotten Realms Commander</option>
    <option value="cbafc">Forgotten Realms Commander (Variantes) / Forgotten Realms Commander (Variants)</option>
    <option value="sh">Fortaleza / Stronghold</option>
    <option value="ala">Fragmentos de Alara / Shards of Alara</option>
    <option value="cs">Frente Fria / Coldsnap</option>
    <option value="fnmp">Friday Night Magic</option>
    <option value="v15">From the Vault: Angels</option>
    <option value="v14">From the Vault: Annihilation</option>
    <option value="fvd">From the Vault: Dragons</option>
    <option value="fve">From the Vault: Exiled</option>
    <option value="fvl">From the Vault: Legends</option>
    <option value="v16">From the Vault: Lore</option>
    <option value="v12">From the Vault: Realms</option>
    <option value="fvr">From the Vault: Relics</option>
    <option value="v17">From the Vault: Transform</option>
    <option value="v13">From the Vault: Twenty</option>
    <option value="gnt">Game Night</option>
    <option value="gn2">Game Night 2019</option>
    <option value="cpm19">Gift Pack (M19)</option>
    <option value="gs1">Global Series: Jiang Yanggu and Mu Yanling</option>
    <option value="grn">Guildas de Ravnica / Guilds of Ravnica</option>
    <option value="med1">Guilds of Ravnica Mythic Edition</option>
    <option value="guru">Guru</option>
    <option value="hachette">Hachette Encyclopedia Inserts</option>
    <option value="salvat">Hachette Encyclopedia Inserts</option>
    <option value="hho">Happy Holidays</option>
    <option value="h17">Hascon 2017</option>
    <option value="h18">Heroes of the Realm 2018</option>
    <option value="h19">Heroes of the Realm 2019</option>
    <option value="ha1">Historic Anthology 1</option>
    <option value="ha2">Historic Anthology 2</option>
    <option value="ha3">Historic Anthology 3</option>
    <option value="ha4">Historic Anthology 4 / Historic Anthology 4</option>
    <option value="ha5">Historic Anthology 5</option>
    <option value="hjcc">Hobby Japan Commemorative Cards</option>
    <option value="hou">Hora da Devastação / Hour of Devastation</option>
    <option value="ima">Iconic Masters</option>
    <option value="iko">Ikoria: Terra de Colossos / Ikoria: Lair of Behemoths</option>
    <option value="piko">Ikoria: Terra de Colossos (Promo) / Ikoria: Lair of Behemoths (Promo)</option>
    <option value="ciko">Ikoria: Terra de Colossos (Variantes) / Ikoria: Lair of Behemoths (Variants)</option>
    <option value="isd">Innistrad / Innistrad</option>
    <option value="mid">Innistrad: Caçada à Meia-noite / Innistrad: Midnight Hunt</option>
    <option value="asmid">Innistrad: Caçada à Meia-noite (Art Series) / Innistrad: Midnight Hunt (Art Series)</option>
    <option value="vmic">Innistrad: Caçada à Meia-noite (Commander Variantes) / Innistrad: Midnight Hunt (Commander Variants)</option>
    <option value="mic">Innistrad: Caçada à Meia-noite (Commander) / Innistrad: Midnight Hunt (Commander)</option>
    <option value="prmid">Innistrad: Caçada à Meia-noite (Promo) / Innistrad: Midnight Hunt (Promo)</option>
    <option value="cbmid">Innistrad: Caçada à Meia-noite (Variantes) / Innistrad: Midnight Hunt (Variants)</option>
    <option value="dbl">Innistrad: Double Feature</option>
    <option value="vow">Innistrad: Voto Carmesim / Innistrad: Crimson Vow</option>
    <option value="asvow">Innistrad: Voto Carmesim (Art Series) / Innistrad: Crimson Vow (Art Series)</option>
    <option value="vvoc">Innistrad: Voto Carmesim (Commander Variantes) / Innistrad: Crimson Vow (Commander Variants)</option>
    <option value="voc">Innistrad: Voto Carmesim (Commander) / Innistrad: Crimson Vow (Commander)</option>
    <option value="prvow">Innistrad: Voto Carmesim (Promo) / Innistrad: Crimson Vow (Promo)</option>
    <option value="vvow">Innistrad: Voto Carmesim (Variantes) / Innistrad: Crimson Vow (Variants)</option>
    <option value="di">Insurreição / Dissension</option>
    <option value="cedi">International Collectors' Edition</option>
    <option value="itp">Introductory Two-Player Set</option>
    <option value="in">Invasão / Invasion</option>
    <option value="on">Investida / Onslaught</option>
    <option value="xln">Ixalan</option>
    <option value="jarena">Japan Arena League</option>
    <option value="jjt">Japan Junior Tournament</option>
    <option value="jre">Japanese Release Events</option>
    <option value="jatc">JingHe Age Token Cards</option>
    <option value="j20">Judge Gift Cards 2020</option>
    <option value="j21">Judge Gift Cards 2021</option>
    <option value="p22">Judge Gift Cards 2022</option>
    <option value="jr">Judge Gift Program</option>
    <option value="ju">Julgamento / Judgment</option>
    <option value="jmp">Jumpstart</option>
    <option value="ajmp">Jumpstart Arena Exclusives</option>
    <option value="maj21">Jumpstart: Historic Horizons</option>
    <option value="jsr">Junior Series</option>
    <option value="ogw">Juramento das Sentinelas / Oath of the Gatewatch</option>
    <option value="kld">Kaladesh</option>
    <option value="klr">Kaladesh Remastered</option>
    <option value="khm">Kaldheim</option>
    <option value="prkhm">Kaldheim (Promo)</option>
    <option value="cbkhm">Kaldheim (Variantes) / Kaldheim (Variants)</option>
    <option value="khc">Kaldheim Commander</option>
    <option value="neo">Kamigawa: Dinastia Neon / Kamigawa: Neon Dynasty</option>
    <option value="asneo">Kamigawa: Dinastia Neon (Art Series) / Kamigawa: Neon Dynasty (Art Series)</option>
    <option value="vnec">Kamigawa: Dinastia Neon (Commander Variantes) / Kamigawa: Neon Dynasty (Commander Variants)</option>
    <option value="nec">Kamigawa: Dinastia Neon (Commander) / Kamigawa: Neon Dynasty (Commander)</option>
    <option value="pneo">Kamigawa: Dinastia Neon (Promo) / Kamigawa: Neon Dynasty (Promo)</option>
    <option value="vneo">Kamigawa: Dinastia Neon (Variantes) / Kamigawa: Neon Dynasty (Variants)</option>
    <option value="ktk">Khans de Tarkir / Khans of Tarkir</option>
    <option value="gk2a">Kit de Guilda: Azorius / Guild Kit: Azorius</option>
    <option value="gk1b">Kit de Guilda: Boros / Guild Kit: Boros</option>
    <option value="gk1d">Kit de Guilda: Dimir / Guild Kit: Dimir</option>
    <option value="gk1g">Kit de Guilda: Golgari / Guild Kit: Golgari</option>
    <option value="gk2g">Kit de Guilda: Gruul / Guild Kit: Gruul</option>
    <option value="gk1i">Kit de Guilda: Izzet / Guild Kit: Izzet</option>
    <option value="gk2o">Kit de Guilda: Orzhov / Guild Kit: Orzhov</option>
    <option value="gk2r">Kit de Guilda: Rakdos / Guild Kit: Rakdos</option>
    <option value="gk1s">Kit de Guilda: Selesnya / Guild Kit: Selesnya</option>
    <option value="gk2s">Kit de Guilda: Simic / Guild Kit: Simic</option>
    <option value="dgm">Labirinto do Dragão / Dragon's Maze</option>
    <option value="la">League</option>
    <option value="rna">Lealdade em Ravnica / Ravnica Allegiance</option>
    <option value="dcilm">Legend Membership</option>
    <option value="lg">Legends</option>
    <option value="le">Legiões / Legions</option>
    <option value="al">Limited Edition Alpha</option>
    <option value="be">Limited Edition Beta</option>
    <option value="lw">Lorwyn / Lorwyn</option>
    <option value="emn">Lua Arcana / Eldritch Moon</option>
    <option value="m10">Magic 2010 / Magic 2010</option>
    <option value="m11">Magic 2011 / Magic 2011</option>
    <option value="m12">Magic 2012 / Magic 2012</option>
    <option value="m13">Magic 2013 / Magic 2013</option>
    <option value="m14">Magic 2014 / Magic 2014</option>
    <option value="m15">Magic 2015</option>
    <option value="mgdc">Magic Game Day Cards</option>
    <option value="ori">Magic Origens / Magic Origins</option>
    <option value="mprp">Magic Player Rewards</option>
    <option value="mpsh">Magic Premiere Shop 2005</option>
    <option value="mps06">Magic Premiere Shop 2006</option>
    <option value="mps07">Magic Premiere Shop 2007</option>
    <option value="mps08">Magic Premiere Shop 2008</option>
    <option value="mps09">Magic Premiere Shop 2009</option>
    <option value="mps10">Magic Premiere Shop 2010</option>
    <option value="mps11">Magic Premiere Shop 2011</option>
    <option value="mss">Magic Scholarship Series</option>
    <option value="mlp">Magic: The Gathering Launch Parties</option>
    <option value="gpx">MagicFest / GP / Command Fest</option>
    <option value="mfpf20">MagicFest 2020</option>
    <option value="mm">Máscara de Mercádia / Mercadian Masques</option>
    <option value="mpsakh">Masterpiece Series: Amonkhet Invocations</option>
    <option value="mpskld">Masterpiece Series: Kaladesh Inventions</option>
    <option value="exp">Masterpiece Series: Zendikar Expeditions</option>
    <option value="a25">Masters 25</option>
    <option value="dembp">Media Inserts</option>
    <option value="itmbp">Media Inserts</option>
    <option value="mbp">Media Inserts (EN)</option>
    <option value="jpmbp">Media Inserts (JP)</option>
    <option value="mr">Miragem / Mirage</option>
    <option value="mi">Mirrodin / Mirrodin</option>
    <option value="mbs">Mirrodin Sitiada / Mirrodin Besieged</option>
    <option value="md1">Modern Event Deck</option>
    <option value="mh1">Modern Horizons</option>
    <option value="mh2">Modern Horizons 2</option>
    <option value="asmh2">Modern Horizons 2 (Art Series)</option>
    <option value="ofmh2">Modern Horizons 2 (Moldura Antiga) / Modern Horizons 2 (Old Frame)</option>
    <option value="prmh2">Modern Horizons 2 (Promo)</option>
    <option value="skmh2">Modern Horizons 2 (Sketch)</option>
    <option value="cbmh2">Modern Horizons 2 (Variantes) / Modern Horizons 2 (Variants)</option>
    <option value="mma">Modern Masters</option>
    <option value="mm2">Modern Masters 2015</option>
    <option value="mm3">Modern Masters 2017</option>
    <option value="med">MTGO Masters Edition</option>
    <option value="me2">MTGO Masters Edition II</option>
    <option value="me3">MTGO Masters Edition III</option>
    <option value="me4">MTGO Masters Edition IV</option>
    <option value="mgbc">Multiverse Gift Box Cards</option>
    <option value="mb1">Mystery Booster</option>
    <option value="cmb2">Mystery Booster Convention Edition</option>
    <option value="cmb1">Mystery Booster Playtest Cards</option>
    <option value="mcq">Mythic Championship Qualifier</option>
    <option value="bng">Nascidos dos Deuses / Born of the Gods</option>
    <option value="ne">Nêmesis / Nemesis</option>
    <option value="9e">Nona Edição - Kit Básico / Ninth Edition</option>
    <option value="9eb">Nona Edição Box Set / Ninth Edition Box Set</option>
    <option value="ncc">Nova Capenna Commander / New Capenna Commander</option>
    <option value="tncc">Nova Capenna Commander (Tokens) / New Capenna Commander (Tokens)</option>
    <option value="vncc">Nova Capenna Commander (Variantes) / New Capenna Commander (Variants)</option>
    <option value="nph">Nova Phyrexia / New Phyrexia</option>
    <option value="ud">O Destino de Urza / Urza's Destiny</option>
    <option value="ul">O Legado de Urza / Urza's Legacy</option>
    <option value="od">Odisséia / Odyssey</option>
    <option value="8e">Oitava Edição - Kit Básico / Eighth Edition</option>
    <option value="8eb">Oitava Edição Box Set / Eighth Edition Box Set</option>
    <option value="oh9">Open House</option>
    <option value="gp">Pacto das Guildas / Guildpact</option>
    <option value="shm">Pântano Sombrio / Shadowmoor</option>
    <option value="pch">Planechase</option>
    <option value="pc2">Planechase 2012 Edition</option>
    <option value="pca">Planechase Anthology</option>
    <option value="pw1">Planeswalker Weekend</option>
    <option value="ptg">Ponies: The Galloping</option>
    <option value="po">Portal</option>
    <option value="pot">Portal Demogame</option>
    <option value="po2">Portal Segunda Era / Portal Second Age</option>
    <option value="p3k">Portal Three Kingdoms</option>
    <option value="gtc">Portões Violados / Gatecrash</option>
    <option value="prm">Premier Play</option>
    <option value="pd2">Premium Deck Series: Fire and Lightning</option>
    <option value="pd3">Premium Deck Series: Graveborn</option>
    <option value="pds">Premium Deck Series: Slivers</option>
    <option value="ptc">Prerelease Events</option>
    <option value="pro">Pro Tour</option>
    <option value="ptd">Pro Tour Decks</option>
    <option value="pr">Profecia / Prophecy</option>
    <option value="pbrif">Promo - Bring-a-Friend</option>
    <option value="pwelb">Promo - Welcome Back</option>
    <option value="prmm20">Promo Pack (M20)</option>
    <option value="4e">Quarta Edição / Fourth Edition</option>
    <option value="4eb">Quarta Edição (BB) / Fourth Edition (BB)</option>
    <option value="5e">Quinta Edição / Fifth Edition</option>
    <option value="med2">Ravnica Allegiance Mythic Edition</option>
    <option value="prwk">Ravnica Weekend</option>
    <option value="rav">Ravnica: A Cidade das Guildas / Ravnica: City of Guilds</option>
    <option value="rdp">Redemption Program</option>
    <option value="rep">Release Events</option>
    <option value="re">Renaissance</option>
    <option value="znr">Renascer de Zendikar / Zendikar Rising</option>
    <option value="prznr">Renascer de Zendikar (Promo) / Zendikar Rising (Promo)</option>
    <option value="cbznr">Renascer de Zendikar (Variantes) / Zendikar Rising (Variants)</option>
    <option value="rtr">Retorno a Ravnica / Return to Ravnica</option>
    <option value="avr">Retorno de Avacyn / Avacyn Restored</option>
    <option value="rv">Revised Edition</option>
    <option value="rvb">Revised Edition (BB)</option>
    <option value="summer">Revised Edition (Summer Magic Edgar)</option>
    <option value="aer">Revolta do Éter / Aether Revolt</option>
    <option value="ri">Rinascimento</option>
    <option value="rix">Rivais de Ixalan / Rivals of Ixalan</option>
    <option value="snc">Ruas de Nova Capenna / Streets of New Capenna</option>
    <option value="adsnc">Ruas de Nova Capenna (Art Deco) / Streets of New Capenna (Art Deco)</option>
    <option value="assnc">Ruas de Nova Capenna (Art Series) / Streets of New Capenna (Art Series)</option>
    <option value="blsnc">Ruas de Nova Capenna (Borderless) / Streets of New Capenna (Borderless)</option>
    <option value="fesnc">Ruas de Nova Capenna (Foil Etched / Gilded Foil) / Streets of New Capenna (Foil Etched / Gilded Foil)</option>
    <option value="gasnc">Ruas de Nova Capenna (Golden Age) / Streets of New Capenna (Golden Age)</option>
    <option value="psnc">Ruas de Nova Capenna (Promo) / Streets of New Capenna (Promo)</option>
    <option value="sssnc">Ruas de Nova Capenna (Skyscraper) / Streets of New Capenna (Skyscraper)</option>
    <option value="tsnc">Ruas de Nova Capenna (Tokens) / Streets of New Capenna (Tokens)</option>
    <option value="sok">Salvadores Kamigawa / Saviors of Kamigawa</option>
    <option value="ps11">Salvat 2011</option>
    <option value="s15">SDCC 2015</option>
    <option value="s16">SDCC 2016</option>
    <option value="s17">SDCC 2017</option>
    <option value="s18">SDCC 2018</option>
    <option value="s19">SDCC 2019</option>
    <option value="sld">Secret Lair Drop Series</option>
    <option value="sld5">Secret Lair Drop Series: &lt;explosion sounds&gt; / Secret Lair Drop Series: &lt;explosion sounds&gt;</option>
    <option value="sld71">Secret Lair Drop Series: Arcane / Secret Lair Drop Series: Arcane</option>
    <option value="sld72">Secret Lair Drop Series: Arcane: Lands / Secret Lair Drop Series: Arcane: Lands</option>
    <option value="sld112">Secret Lair Drop Series: Artist Series: Chris Rahn</option>
    <option value="sld57">Secret Lair Drop Series: Artist Series: Johannes Voss / Secret Lair Drop Series: Artist Series: Johannes Voss</option>
    <option value="sld111">Secret Lair Drop Series: Artist Series: Livia Prima</option>
    <option value="sld102">Secret Lair Drop Series: Artist Series: Magali Villeneuve / Secret Lair Drop Series: Artist Series: Magali Villeneuve</option>
    <option value="sld103">Secret Lair Drop Series: Artist Series: Sidharth Chaturvedi / Secret Lair Drop Series: Artist Series: Sidharth Chaturvedi</option>
    <option value="sld109">Secret Lair Drop Series: Artist Series: The Tokyo Lands</option>
    <option value="sld58">Secret Lair Drop Series: Artist Series: Thomas Baxa / Secret Lair Drop Series: Artist Series: Thomas Baxa</option>
    <option value="sld114">Secret Lair Drop Series: Artist Series: Volkan Baga</option>
    <option value="sld104">Secret Lair Drop Series: Artist Series: Wayne Reynolds / Secret Lair Drop Series: Artist Series: Wayne Reynolds</option>
    <option value="sld76">Secret Lair Drop Series: Crocodile Jackson's Monstrous Menagerie / Secret Lair Drop Series: Crocodile Jackson's Monstrous Menagerie</option>
    <option value="sld54">Secret Lair Drop Series: Dan Frazier is Back: The Allied Signets / Secret Lair Drop Series: Dan Frazier is Back: The Allied Signets</option>
    <option value="sld55">Secret Lair Drop Series: Dan Frazier is Back: The Enemy Signets / Secret Lair Drop Series: Dan Frazier is Back: The Enemy Signets</option>
    <option value="sld69">Secret Lair Drop Series: Extra Life 2021 / Secret Lair Drop Series: Extra Life 2021</option>
    <option value="sld77">Secret Lair Drop Series: Far Out, Man / Secret Lair Drop Series: Far Out, Man</option>
    <option value="sld75">Secret Lair Drop Series: Fblthp: Completely, Utterly, Totally Lost / Secret Lair Drop Series: Fblthp: Completely, Utterly, Totally Lost</option>
    <option value="sld105">Secret Lair Drop Series: Finally! Left-Handed Magic Cards / Secret Lair Drop Series: Finally! Left-Handed Magic Cards</option>
    <option value="sld115">Secret Lair Drop Series: Fortnite / Secret Lair Drop Series: Fortnite</option>
    <option value="sld116">Secret Lair Drop Series: Fortnite: Lands and Locations / Secret Lair Drop Series: Fortnite: Lands and Locations</option>
    <option value="sld79">Secret Lair Drop Series: Heads I Win, Tails You Lose / Secret Lair Drop Series: Heads I Win, Tails You Lose</option>
    <option value="sld108">Secret Lair Drop Series: Here be Dragons</option>
    <option value="sld93">Secret Lair Drop Series: Introducing: Kaito Shizuki / Secret Lair Drop Series: Introducing: Kaito Shizuki</option>
    <option value="sld106">Secret Lair Drop Series: Just Some Totally Normal Guys / Secret Lair Drop Series: Just Some Totally Normal Guys</option>
    <option value="sld56">Secret Lair Drop Series: Kamigawa Ink / Secret Lair Drop Series: Kamigawa Ink</option>
    <option value="sld94">Secret Lair Drop Series: Kamigawa: The Manga: The Cards / Secret Lair Drop Series: Kamigawa: The Manga: The Cards</option>
    <option value="sld95">Secret Lair Drop Series: Li’l Walkers / Secret Lair Drop Series: Li’l Walkers</option>
    <option value="sld59">Secret Lair Drop Series: Math is for Blockers / Secret Lair Drop Series: Math is for Blockers</option>
    <option value="sld62">Secret Lair Drop Series: Mirrodinsanity / Secret Lair Drop Series: Mirrodinsanity</option>
    <option value="sld63">Secret Lair Drop Series: Monster Anatomy 101 / Secret Lair Drop Series: Monster Anatomy 101</option>
    <option value="sld64">Secret Lair Drop Series: Monster Movie Marathon / Secret Lair Drop Series: Monster Movie Marathon</option>
    <option value="sld53">Secret Lair Drop Series: Mother's Day 2021 / Secret Lair Drop Series: Mother's Day 2021</option>
    <option value="sld70">Secret Lair Drop Series: MSCHF / Secret Lair Drop Series: MSCHF</option>
    <option value="sld52">Secret Lair Drop Series: Phyrexian Praetors: Compleat Edition / Secret Lair Drop Series: Phyrexian Praetors: Compleat Edition</option>
    <option value="sld96">Secret Lair Drop Series: Pictures of the Floating World / Secret Lair Drop Series: Pictures of the Floating World</option>
    <option value="sld78">Secret Lair Drop Series: PixelSnowLands / Secret Lair Drop Series: PixelSnowLands</option>
    <option value="sld107">Secret Lair Drop Series: Pride Across the Multiverse / Secret Lair Drop Series: Pride Across the Multiverse</option>
    <option value="sld68">Secret Lair Drop Series: Purrfection / Secret Lair Drop Series: Purrfection</option>
    <option value="sld65">Secret Lair Drop Series: Read the Fine Print / Secret Lair Drop Series: Read the Fine Print</option>
    <option value="sld113">Secret Lair Drop Series: Rule the Room</option>
    <option value="sld92">Secret Lair Drop Series: Secret Lair x Street Fighter / Secret Lair Drop Series: Secret Lair x Street Fighter</option>
    <option value="sld97">Secret Lair Drop Series: Shades Not Included / Secret Lair Drop Series: Shades Not Included</option>
    <option value="sld66">Secret Lair Drop Series: Showcase: Midnight Hunt / Secret Lair Drop Series: Showcase: Midnight Hunt</option>
    <option value="sld98">Secret Lair Drop Series: Showcase: Neon Dynasty / Secret Lair Drop Series: Showcase: Neon Dynasty</option>
    <option value="sld100">Secret Lair Drop Series: Showcase: Streets of New Capenna Gilded Foil Edition / Secret Lair Drop Series: Showcase: Streets of New Capenna Gilded Foil Edition</option>
    <option value="sld50">Secret Lair Drop Series: Special Guest: Fiona Staples / Secret Lair Drop Series: Special Guest: Fiona Staples</option>
    <option value="sld51">Secret Lair Drop Series: Special Guest: Jen Bartel / Secret Lair Drop Series: Special Guest: Jen Bartel</option>
    <option value="sld110">Secret Lair Drop Series: Special Guest: Kelogsloops</option>
    <option value="sld101">Secret Lair Drop Series: Special Guest: Matt Jukes / Secret Lair Drop Series: Special Guest: Matt Jukes</option>
    <option value="sld99">Secret Lair Drop Series: Special Guest: Yuko Shimizu / Secret Lair Drop Series: Special Guest: Yuko Shimizu</option>
    <option value="sld61">Secret Lair Drop Series: Stranger Things / Secret Lair Drop Series: Stranger Things</option>
    <option value="sld60">Secret Lair Drop Series: Teferi's Time Trouble / Secret Lair Drop Series: Teferi's Time Trouble</option>
    <option value="sld81">Secret Lair Drop Series: The Astrology Lands: Aquarius / Secret Lair Drop Series: The Astrology Lands: Aquarius</option>
    <option value="sld83">Secret Lair Drop Series: The Astrology Lands: Aries / Secret Lair Drop Series: The Astrology Lands: Aries</option>
    <option value="sld86">Secret Lair Drop Series: The Astrology Lands: Cancer / Secret Lair Drop Series: The Astrology Lands: Cancer</option>
    <option value="sld80">Secret Lair Drop Series: The Astrology Lands: Capricorn / Secret Lair Drop Series: The Astrology Lands: Capricorn</option>
    <option value="sld85">Secret Lair Drop Series: The Astrology Lands: Gemini</option>
    <option value="sld82">Secret Lair Drop Series: The Astrology Lands: Pisces / Secret Lair Drop Series: The Astrology Lands: Pisces</option>
    <option value="sld84">Secret Lair Drop Series: The Astrology Lands: Taurus / Secret Lair Drop Series: The Astrology Lands: Taurus</option>
    <option value="sld74">Secret Lair Drop Series: The Dracula Lands / Secret Lair Drop Series: The Dracula Lands</option>
    <option value="sld67">Secret Lair Drop Series: Thrilling Tales of the Undead / Secret Lair Drop Series: Thrilling Tales of the Undead</option>
    <option value="sld73">Secret Lair Drop Series: Welcome to Castle Dracula / Secret Lair Drop Series: Welcome to Castle Dracula</option>
    <option value="slx">Secret Lair Exclusives</option>
    <option value="slu">Secret Lair: Ultimate Edition</option>
    <option value="7e">Sétima Edição / Seventh Edition</option>
    <option value="6e">Sexta Edição Classica / Classic Sixth Edition</option>
    <option value="ss3">Signature Spellbook: Chandra</option>
    <option value="ss2">Signature Spellbook: Gideon</option>
    <option value="ss1">Signature Spellbook: Jace</option>
    <option value="soi">Sombras em Innistrad / Shadows over Innistrad</option>
    <option value="ssp">Standard Showdown 2017</option>
    <option value="ssp18">Standard Showdown 2018</option>
    <option value="st">Starter 1999</option>
    <option value="st2k">Starter 2000 / Starter 2000</option>
    <option value="sc9">Store Championship</option>
    <option value="sta">Strixhaven: Arquivo Místico / Strixhaven: Mystical Archive</option>
    <option value="jpsta">Strixhaven: Arquivo Místico (Japonês) / Strixhaven: Mystical Archive (Japanese)</option>
    <option value="asstx">Strixhaven: Art Series</option>
    <option value="stx">Strixhaven: Escola de Magos / Strixhaven: School of Mages</option>
    <option value="prstx">Strixhaven: Escola de Magos (Promo) / Strixhaven (Promo)</option>
    <option value="cbstx">Strixhaven: Escola de Magos (Variantes) / Strixhaven (Variants)</option>
    <option value="sum">Summer of Magic</option>
    <option value="sus">Super Series</option>
    <option value="tpr">Tempest Remastered</option>
    <option value="tp">Tempestade / Tempest</option>
    <option value="hl">Terras Natais / Homelands</option>
    <option value="dk">The Dark</option>
    <option value="plist">The List</option>
    <option value="ths">Theros / Theros</option>
    <option value="thb">Theros Além da Morte / Theros: Beyond Death</option>
    <option value="prthb">Theros Além da Morte (Promo) / Theros: Beyond Death (Promo)</option>
    <option value="cthb">Theros Além da Morte (Variantes) / Theros: Beyond Death (Variants)</option>
    <option value="tsts">Time Spiral Timeshifted / Time Spiral Timeshifted</option>
    <option value="tr">Tormento / Torment</option>
    <option value="bok">Traidores de Kamigawa / Betrayers of Kamigawa</option>
    <option value="eld">Trono de Eldraine / Throne of Eldraine</option>
    <option value="preld">Trono de Eldraine (Promo) / Throne of Eldraine (Promo)</option>
    <option value="celd">Trono de Eldraine (Variantes) / Throne of Eldraine (Variants)</option>
    <option value="thgt">Two-Headed Giant Tournament</option>
    <option value="ugin">Ugin's Fate / Ugin's Fate</option>
    <option value="umap">Ultimate Box Topper</option>
    <option value="uma">Ultimate Masters</option>
    <option value="unf">Unfinity</option>
    <option value="prunf">Unfinity (Promo)</option>
    <option value="vunf">Unfinity (Variants)</option>
    <option value="ug">Unglued</option>
    <option value="uh">Unhinged</option>
    <option value="uhaa">Unhinged Alternate Foils</option>
    <option value="un">Unlimited Edition</option>
    <option value="und">Unsanctioned</option>
    <option value="ust">Unstable</option>
    <option value="vgd">Vanguard</option>
    <option value="jou">Viagem para Nyx / Journey into Nyx</option>
    <option value="vma">Vintage Masters</option>
    <option value="fut">Visão do Futuro / Future Sight</option>
    <option value="vi">Visões / Visions</option>
    <option value="med3">War of the Spark Mythic Edition</option>
    <option value="40k">Warhammer 40.000</option>
    <option value="w16">Welcome Deck 2016</option>
    <option value="w17">Welcome Deck 2017</option>
    <option value="pwp21">Wizards Play Network 2021</option>
    <option value="pwp22">Wizards Play Network 2022</option>
    <option value="wcd">World Championship Decks</option>
    <option value="wmcq">World Magic Cup Qualifiers</option>
    <option value="wrl">Worlds</option>
    <option value="wotc">WotC Online Store</option>
    <option value="grc">WPN/Gateway</option>
    <option value="zen">Zendikar / Zendikar</option>
    <option value="znc">Zendikar Rising Commander</option>
    <option value="zne">Zendikar Rising Expeditions</option>